### ISSUE TITLE
LibreOffice "latest" is incorrect

### ISSUE THREAD

**Issue by hfiguiere** [fortwire/Who-Updates#1]
The dashboard claim that LibreOffice 7 is out. 

![image](https://user-images.githubusercontent.com/114441/86685579-9b222e00-bfd1-11ea-9c00-8eca290118a9.png)

But that's not the case if you visit LibreOffice website

![image](https://user-images.githubusercontent.com/114441/86685447-7ded5f80-bfd1-11ea-8575-3e1f1efd689d.png)

**Comment by fortwire** [comment]
The latest column is all based on Repology. Check it here. https://repology.org/project/libreoffice/information
The script just looks for <span class="version version-big version-newest">X.X.X.X</span> (I.e. the green highlighted number).
Maybe I should to add some sort of additional check in the code for these anomalies.
E.g. if repology looks odd, check from the official vendor.

**Comment by fortwire** [comment]
I've noticed the repology sorts itself out with incorrect versions in a few days.

Libreoffice looks right now at 6.4.5
