### ISSUE TITLE
Kdenlive "Latest" is incorrect

### ISSUE THREAD

**Issue by hfiguiere** [fortwire/Who-Updates#2]
Kdenlive is still at 20.04.2 not 20.04.3. Seems like they are getting the wrong info:

See tags in the repository:
https://invent.kde.org/multimedia/kdenlive/-/tags

(the fact the appdata is changed in the branch is irrelevant, it is the tag that matters)

**Comment by fortwire** [comment]
Thanks for letting me know. It seems relying on https://repology.org/project/kdenlive/information for the latest version isn't accurate for some software.

**Comment by fortwire** [comment]
The link is showing 20.04.3. There seems to be a lag time. I'll keep an eye on it.

https://invent.kde.org/multimedia/kdenlive/-/tags
![kdenlive](https://user-images.githubusercontent.com/65652976/87113883-9e0f6e00-c2b2-11ea-96ad-4b879d2c2fc1.png)

**Comment by hfiguiere** [comment]
It wasn't there when I did check. Could have been pushed in between. Not sure.
